{
  "properties" : { },
  "id" : "d6dbf8b1fd2e47e2bcae33835a6fa1db",
  "script" : null,
  "groupId" : "d03557cc2f2c4006aba394f1b4b035eb",
  "name" : "product",
  "createTime" : 1699247682594,
  "updateTime" : null,
  "lock" : null,
  "createBy" : null,
  "updateBy" : null,
  "path" : "/productList",
  "method" : "POST",
  "parameters" : [ {
    "name" : "accountId",
    "value" : null,
    "description" : null,
    "required" : false,
    "dataType" : "Integer",
    "type" : null,
    "defaultValue" : "erupt",
    "validateType" : null,
    "error" : null,
    "expression" : null,
    "children" : null
  } ],
  "options" : [ ],
  "requestBody" : null,
  "headers" : [ ],
  "paths" : [ ],
  "responseBody" : null,
  "description" : null,
  "requestBodyDefinition" : null,
  "responseBodyDefinition" : null
}
================================
return 'Hello magic-api'