# application.yml写法
spring:
  datasource:
    url: jdbc:mysql://database-1.cosxrbrmnajg.ap-northeast-2.rds.amazonaws.com:3306/erupt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql